### ISSUE TITLE
Update to Spring 4 and Java 1.8

### ISSUE THREAD

**Issue by danizen** [EBISPOT/lodestar#18]
Spring version 3 framework will hit end of life Dec 31, 2016.  

I've tried building lodestar as follows, and found it still works. not just the build, but accessing it over a network once installed over Tomcat, and running queries.

```
mvn -Pvirtuoso -Dorg.springframework.version=4.3.3.RELEASE clean package
```

Any reason not to upgrade?

**Comment by simonjupp** [comment]
I agree, we should upgrade it. In fact we probably want to move to Spring Boot and do away with the XML based configuration. Someone in my team is going to start looking into this soon, but if you want to make a start please go ahead.

**Comment by danizen** [comment]
I am unable to move to Spring Boot, or get rid of the XML based configuration entirely.   I have a bunch of security upgrades in `https://github.com/HHS/lodestar` under the feature/security-scans branch.   I'll submit a pull request to clarify what changes, and you guys can help clarify which of these versions should be pushed up into the parent `pom.xml`.

**Comment by simonjupp** [comment]
I'm fine to upgrade spring if you want to create the pull request. 

Out of interest, what's he issue with spring boot?

**Comment by danizen** [comment]
I just don't know Spring boot.   I have to learn it before I can upgrade to it.

**Comment by danizen** [comment]
With the security update, you did update to Spring 4.3.3.RELEASE, so I'm closing this.   I'll create another to upgrade to Spring Boot.
