### ISSUE TITLE
Link to documentation and stable releases

### ISSUE THREAD

**Issue by agbeltran** [EBISPOT/lodestar#19]
Hi @simonjupp 
The link in the README file is no longer valid: http://www.ebi.ac.uk/fgpt/sw/lodestar
Likewise the link in the RDF platform documentation (https://www.ebi.ac.uk/rdf/documentation/infrastructure): https://www.ebi.ac.uk/rdf/fgpt/sw/lodestar/
Has the page moved somewhere else?
Thanks

**Comment by simonjupp** [comment]
Hi Alejandra, 

Yes, sorry the fgpt group is no more and we moved our webspace to spot but haven't finished migrating all the sites over. 

I'm planning to move lodestar docs to github pages, for now you can access the documentation here http://ebispot.github.io/lodestar/lodestar.html

**Comment by agbeltran** [comment]
Thanks Simon!
