### ISSUE TITLE
Documentation is missing and links are stale

### ISSUE THREAD

**Issue by ianwdunlop** [EBISPOT/lodestar#24]
Hi Simon et al. The lodestar docs at http://www.ebi.ac.uk/fgpt/sw/lodestar seem to have gone missing. The lodestar link on https://www.ebi.ac.uk/rdf/documentation/infrastructure to https://www.ebi.ac.uk/rdf/fgpt/sw/lodestar/ has also become stale. Are there any lodestar deployment/setup docs available anywhere?

**Comment by simonjupp** [comment]
Hi Ian, 
Yes, it's moved, I need to update links. 

http://ebispot.github.io/lodestar/

**Comment by ianwdunlop** [comment]
Thanks Simon. Much appreciated. It was fairly easy to get running anyway after I added `lode.explorer.service.baseuri=http://localhost:8080/lodestar` to /WEB-INF/classes/lode.properties
